from pycell.client import VizierDBClient as VizierDBClient
from typing import Any, Optional

target_client: Optional[VizierDBClient]
bokeh_resources: Any

def python_cell_preload(client: VizierDBClient) -> Any: ...
def python_cell_close() -> None: ...
def vizier_bokeh_load(resources: Any, verbose: Any, hide_banner: Any, load_timeout: Any) -> None: ...
def vizier_bokeh_show(obj: Any, state: Any, notebook_handle: Any) -> None: ...
def vizier_bokeh_app(app: Any, state: Any, notebook_url: Any, **kwargs: Any) -> None: ...
def vizier_matplotlib_render(figure: Any): ...
